Repository 2024-Summer-Bootcamp-Team-O/Backend, pull requests merged in 2024-07, with the labels that each got.

#6 fix: chat 모델 수정
  chat/migrations/0005_chatroom_mz_rank_alter_chatroom_character_and_more.py
  chat/models.py
Labels: Fix

#7 feat: swagger 적용
  Dockerfile
  backend/settings.py
  backend/urls.py
Labels: Feat

#9 refactor: ChatRoom 필드명 수정
  chat/migrations/0006_rename_mz_rank_chatroom_mz_percent_and_more.py
  chat/models.py
Labels: Refactor

#13 fix: erd 수정에 따른 모델 변경
  chat/migrations/0001_initial.py
  chat/models.py
  user/migrations/0001_initial.py
  user/models.py
Labels: Fix

#15 feat: rabbitMQ, celery, redis 환경 구축
  Dockerfile
  backend/celery.py
  backend/settings.py
  docker-compose.yml
Labels: Feat

#17 fix: 모델 이름 수정 및 celery 재설정
  backend/__init__.py
  backend/celery.py
  backend/settings.py
  chat/migrations/0001_initial.py
  chat/models.py
  docker-compose.yml
  requirements.txt
  user/migrations/0001_initial.py
  user/models.py
Labels: Fix

#18 feat:회원가입 기능 추가
  .idea/backend.iml
  .idea/misc.xml
  .idea/watcherTasks.xml
  backend/__pycache__/__init__.cpython-310.pyc
  backend/__pycache__/celery.cpython-310.pyc
  backend/__pycache__/settings.cpython-310.pyc
  backend/__pycache__/urls.cpython-310.pyc
  backend/__pycache__/wsgi.cpython-310.pyc
  chat/__pycache__/__init__.cpython-310.pyc
  chat/__pycache__/admin.cpython-310.pyc
  chat/__pycache__/apps.cpython-310.pyc
  chat/__pycache__/models.cpython-310.pyc
  chat/__pycache__/urls.cpython-310.pyc
  chat/migrations/__pycache__/0001_initial.cpython-310.pyc
  chat/migrations/__pycache__/__init__.cpython-310.pyc
  result/__pycache__/__init__.cpython-310.pyc
  result/__pycache__/admin.cpython-310.pyc
  result/__pycache__/apps.cpython-310.pyc
  result/__pycache__/models.cpython-310.pyc
  result/__pycache__/urls.cpython-310.pyc
  result/migrations/__pycache__/__init__.cpython-310.pyc
  user/__pycache__/__init__.cpython-310.pyc
  user/__pycache__/admin.cpython-310.pyc
  user/__pycache__/apps.cpython-310.pyc
  user/__pycache__/models.cpython-310.pyc
  user/__pycache__/serializers.cpython-310.pyc
  user/__pycache__/urls.cpython-310.pyc
  user/__pycache__/views.cpython-310.pyc
  user/migrations/__pycache__/0001_initial.cpython-310.pyc
  user/migrations/__pycache__/__init__.cpython-310.pyc
  user/serializers.py
  user/urls.py
  user/views.py
Labels: Feat

#19 feat: 로그인/로그아웃 기능 추가
  .idea/watcherTasks.xml
  backend/settings.py
  backend/urls.py
  user/serializers.py
  user/urls.py
  user/views.py
Labels: Feat

#21 fix: 로그인/로그아웃 기능 수정 및 회원가입 기능 보완, gitignore 내용 추가
  .gitignore
  backend/urls.py
  user/serializers.py
  user/views.py
Labels: Fix

#23 feat: jwt 적용
  Dockerfile
  backend/settings.py
  backend/urls.py
  chat/migrations/0001_initial.py
  chat/models.py
  user/migrations/0001_initial.py
  user/models.py
  user/serializers.py
  user/urls.py
  user/views.py
Labels: Feat

#25 fix: erd 변경에 따른 모델 수정
  .idea/dataSources.xml
  chat/migrations/0001_initial.py
  chat/models.py
  user/migrations/0001_initial.py
Labels: Fix

#30 feat: 초기 데이터 저장 파일 작성
  .idea/sqldialects.xml
  .idea/watcherTasks.xml
  chat/migrations/0001_initial.py
  chat/models.py
  docker-compose.yml
  init.sql
  user/migrations/0001_initial.py
Labels: Feat

#33 feat: gpt 연동 후 웹 소켓 및 비동기 처리 구현
  Dockerfile
  backend/asgi.py
  backend/settings.py
  chat/consumers.py
  chat/routing.py
  chat/serializers.py
  chat/tasks.py
  chat/urls.py
  chat/views.py
  init.sql
  requirements.txt
Labels: Feat

#35 feat: 선택지 선택 및 피드백 제공, 피드백은 redis 연동하여 저장기능 구현
  backend/asgi.py
  backend/settings.py
  backend/urls.py
  chat/serializers.py
  chat/urls.py
  chat/views.py
  gpt/__init__.py
  gpt/admin.py
  gpt/apps.py
  gpt/consumers.py
  gpt/migrations/__init__.py
  gpt/models.py
  gpt/routing.py
  gpt/serializers.py
  gpt/tasks.py
  gpt/tests.py
  gpt/urls.py
  gpt/views.py
Labels: Feat

#37 feat: 최종 피드백 프롬프트 작성
  chat/urls.py
  gpt/serializers.py
  gpt/tasks.py
  gpt/urls.py
  gpt/views.py
  user/urls.py
Labels: Feat

#39 feat: 대화 시작 시 캐릭터 정보를 저장하고 상황을 랜덤 배정하는 기능 추가
  .idea/dataSources.xml
  chat/serializers.py
  chat/urls.py
  chat/views.py
  gpt/views.py
  user/serializers.py
Labels: Feat

#40 feat: 비동기 처리 및 웹소켓 처리 테스트 및 구현
  backend/settings.py
  chat/serializers.py
  chat/views.py
  gpt/consumers.py
  gpt/tasks.py
Labels: Feat

#44 feat/#29 피드백 제공 완료 시에 다음 상황 랜덤하게 제공 기능 추가
  chat/serializers.py
  chat/urls.py
  chat/views.py
  gpt/views.py
Labels: Feat

#47 fix: erd 수정 및 기능 수정
  .idea/dataSources.xml
  chat/migrations/0001_initial.py
  chat/models.py
  chat/serializers.py
  chat/templates/index.html
  chat/urls.py
  chat/views.py
  gpt/consumers.py
  gpt/tasks.py
  init.sql
Labels: Fix

#48 feat: LangCain 을 활용한 이전 대화 저장 기능 및 대화형으로 변경
  .idea/watcherTasks.xml
  backend/settings.py
  chat/migrations/0001_initial.py
  chat/models.py
  chat/serializers.py
  chat/templates/index.html
  chat/views.py
  gpt/consumers.py
  gpt/tasks.py
  gpt/urls.py
  gpt/views.py
  init.sql
  requirements.txt
  user/migrations/0001_initial.py
  user/models.py
  user/serializers.py
  user/views.py
Labels: Feat

#51 fix: 피드백과 다음에피소드 api 분리
  .idea/watcherTasks.xml
  chat/templates/index.html
  chat/urls.py
  chat/views.py
  gpt/views.py
Labels: Fix

#53 feat: 대화 종료 시 피드백 데이터베이스에 저장 및 반환
  chat/urls.py
  chat/views.py
Labels: Feat

#56 fix: voice 모델 수정
  chat/migrations/0001_initial.py
  chat/migrations/0002_voice.py
  chat/models.py
  chat/views.py
  gpt/tasks.py
Labels: Fix

#59 fix: 타입스크립트 접근 허용
  backend/settings.py
Labels: Fix

#62 fix: csrf trust 추가
  backend/settings.py
Labels: Fix

#63 feat: S3를 사용하여 사원증 사진 등록 기능 구현
  backend/settings.py
  chat/migrations/0001_initial.py
  chat/models.py
  chat/serializers.py
  chat/templates/index.html
  chat/urls.py
  chat/views.py
  init.sql
  requirements.txt
  user/views.py
Labels: Feat

#65 feat: nginx 적용
  Dockerfile
  backend/settings.py
  chat/templates/index.html
  chat/views.py
  docker-compose.yml
  nginx.conf
  requirements.txt
Labels: Feat

#68 feat: 결과지 상세 조회 기능 추가
  user/urls.py
  user/views.py
Labels: Feat

#69 feat: jwt 인증 일괄 적용
  backend/settings.py
  chat/serializers.py
  chat/views.py
  gpt/serializers.py
  gpt/urls.py
  gpt/views.py
  user/urls.py
  user/views.py
Labels: Feat

#72 fix: answer 응답 띄어쓰기 추가
  backend/settings.py
  gpt/tasks.py
  result/__init__.py
  result/admin.py
  result/apps.py
  result/migrations/__init__.py
  result/models.py
  result/tests.py
  result/urls.py
  result/views.py
Labels: Fix

#74 fix: count 로직 수정
  gpt/views.py
Labels: Fix

#75 feat: 배포용 도커파일 작성
  Dockerfile
  chat/views.py
  docker-compose.prod.yml
  docker-compose.yml
  manage.py
  prometheus/prometheus.yml
  requirements.txt
  rumz/__init__.py
  rumz/asgi.py
  rumz/celery.py
  rumz/settings.py
  rumz/urls.py
  rumz/wsgi.py
Labels: Feat

#77 feat: 결과지 생성 시 이름 반환
  chat/views.py
Labels: Feat

#79 fix: 모니터링 툴 오류 수정
  docker-compose.prod.yml
  docker-compose.yml
  nginx.conf
  requirements.txt
  rumz/settings.py
  rumz/urls.py
Labels: Fix

#81 fix: 배포용 도커파일 수정
  docker-compose.yml
Labels: Fix

#83 feat: https 적용
  chat/serializers.py
  chat/templates/index.html
  chat/urls.py
  chat/views.py
  docker-compose.prod.yml
  nginx.conf
Labels: Feat

#86 fix: ec2 swagger 동작 오류 수정
  docker-compose.prod.yml
  nginx.conf
  rumz/settings.py
  rumz/urls.py
Labels: Fix

#87 feat: S3에 cloud front 적용
  chat/views.py
  rumz/settings.py
  user/views.py
Labels: Feat

#90 feat: CD/CD 적용
  .github/workflows/CD-CD.yml
Labels: Feat

#95 feat: 무중단 배포 구현
  current_version.txt
  deploy.sh
  docker-compose-blue.prod.yml
  docker-compose-green.prod.yml
  nginx.conf
Labels: Feat

#98 fix: redis key값을 각 사용자가 고유하게 가지도록 수정
  chat/views.py
  gpt/consumers.py
  gpt/tasks.py
  gpt/views.py
Labels: Fix

#100 [test/#94] gpt 테스트코드 추가
  gpt/tests.py
Labels: Test

#102 test: chat 테스트 코드 추가
  chat/tests.py
Labels: Test
